import Head from "next/head";
import Navbar from "../../component/navbar";
import Greet from "../../component/greet";
import InputField from "../../component/inputField";
import Division from "../../component/division";

import { useEffect, useState } from "react";

export default function Home() {
  const [data,setData] = useState<any[]>([]);

  useEffect(()=>{
    (async()=>{
       const res = await fetch('/api/blog');
       const data = await res.json();
       setData(data);
    })()
  },[])

  console.log(data);


  return (
    <>
      <Head>
        <title>Legend Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
        <Greet/>
        <Division /> 
        <InputField data={data} />        
    </>
  );
}
