import Head from 'next/head';
import styles from '@/styles/login.module.css';
import { useRef, useState } from 'react';
import { useUserData } from '../context/userData.context';
import HomePage from '../component/homePage';


export default function Home() {
    const [userName, setUserName] = useUserData()!;

    const userRef = useRef<HTMLInputElement>(null);

    const passwordRef = useRef<HTMLInputElement>(null);
    
    // const [toggle, setToggle] = useState(false);

    const handleSubmit = async (e: any) => {
        e.preventDefault();
        const option = {
            method: 'POST',
            body: JSON.stringify({
                username: userRef.current?.value,
                password: passwordRef.current?.value
            })
        };

        console.log('userName is : ' + `${userRef.current?.value}`);
        console.log('password is : ' + `${passwordRef.current?.value}`);

        const res = await fetch('/api/login', option);
        const data = await res.json();
        if (!data.error) {
            alert(data.message);
            console.log(data.message, data.login);
        }

        if (data.login) {
            setUserName(`${userRef.current?.value}`);
            localStorage.setItem('name',(`${userRef.current?.value}`));
            console.log("username-index" + `${userName}`);
        }
    };

    return (
        <>
            <Head>
                <title>Legend Blogs</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {userName ? (
                <HomePage />
            ) : (
                <div className={styles.landingPage}>
                    <form onSubmit={handleSubmit} className={styles.loginDetails}>
                        <div className={styles.header}>LOGIN</div>

                        <div className={styles.inputField}>
                            <input
                                type="text"
                                ref={userRef}
                                required
                                autoComplete="off"
                            />
                            <label>Username</label>
                        </div>

                        <div className={styles.inputField}>
                            <input
                                type="password"
                                ref={passwordRef}
                                required
                                autoComplete="off"
                            />
                            <label>Password</label>
                        </div>
                        

                        <button type="submit" className={styles.loginBtn}>
                            Login
                        </button>
                    </form>
                </div>
            )}
        </>
    );
}
